import { LinkCoverSize, ReplyType, TweetType } from '@/types/common';
import type { TweetListResponse } from '@/types/lists';
import type {
  GifImageResponse,
  PollResponse,
  QuoteTweetResponse,
  TweetResponse,
} from '@/types/tweet';

const emptyGifImage: GifImageResponse = { url: '', width: 0, height: 0 };

export const mockTweets: TweetResponse[] = [
  {
    id: '1',
    text: 'Just launched my new project! 🚀 Excited to share it with everyone. Check it out and let me know what you think!',
    tweetType: TweetType.TWEET,
    createdAt: '2025-11-07T10:30:00Z',
    scheduledDate: '',
    addressedUsername: '',
    addressedId: 0,
    addressedTweetId: 0,
    replyType: ReplyType.EVERYONE,
    link: '',
    linkTitle: '',
    linkDescription: '',
    linkCover: '',
    linkCoverSize: LinkCoverSize.SMALL,
    gifImage: emptyGifImage,
    author: {
      id: 1,
      fullName: 'John Doe',
      username: 'johndoe',
      avatar: 'https://i.pravatar.cc/150?img=1',
      pinnedTweetId: 0,
      isPrivateProfile: false,
      isFollower: false,
      isMyProfileBlocked: false,
      isUserBlocked: false,
      isUserMuted: false,
    },
    images: [],
    imageDescription: '',
    taggedImageUsers: [],
    quoteTweet: {} as QuoteTweetResponse,
    tweetList: {} as TweetListResponse,
    poll: {} as PollResponse,
    retweetsCount: 45,
    likesCount: 128,
    repliesCount: 23,
    quotesCount: 5,
    isDeleted: false,
    isTweetLiked: false,
    isTweetRetweeted: false,
    isUserFollowByOtherUser: true,
    isTweetDeleted: false,
    isTweetBookmarked: false,
  },
  {
    id: '2',
    text: 'Beautiful day for coding! ☀️ Working on some exciting features. What are you all working on today?',
    tweetType: TweetType.TWEET,
    createdAt: '2025-11-07T09:15:00Z',
    scheduledDate: '',
    addressedUsername: '',
    addressedId: 0,
    addressedTweetId: 0,
    replyType: ReplyType.EVERYONE,
    link: '',
    linkTitle: '',
    linkDescription: '',
    linkCover: '',
    linkCoverSize: LinkCoverSize.SMALL,
    gifImage: emptyGifImage,
    author: {
      id: 2,
      fullName: 'Jane Smith',
      username: 'janesmith',
      avatar: 'https://i.pravatar.cc/150?img=5',
      pinnedTweetId: 0,
      isPrivateProfile: false,
      isFollower: true,
      isMyProfileBlocked: false,
      isUserBlocked: false,
      isUserMuted: false,
    },
    images: [],
    imageDescription: '',
    taggedImageUsers: [],
    quoteTweet: {} as QuoteTweetResponse,
    tweetList: {} as TweetListResponse,
    poll: {} as PollResponse,
    retweetsCount: 12,
    likesCount: 89,
    repliesCount: 15,
    quotesCount: 2,
    isDeleted: false,
    isTweetLiked: true,
    isTweetRetweeted: false,
    isUserFollowByOtherUser: true,
    isTweetDeleted: false,
    isTweetBookmarked: false,
  },
  {
    id: '3',
    text: 'Quick tip: Always write clean code. Your future self will thank you! 💡 #coding #tips',
    tweetType: TweetType.TWEET,
    createdAt: '2025-11-07T08:00:00Z',
    scheduledDate: '',
    addressedUsername: '',
    addressedId: 0,
    addressedTweetId: 0,
    replyType: ReplyType.EVERYONE,
    link: '',
    linkTitle: '',
    linkDescription: '',
    linkCover: '',
    linkCoverSize: LinkCoverSize.SMALL,
    gifImage: emptyGifImage,
    author: {
      id: 3,
      fullName: 'Mike Johnson',
      username: 'mikej',
      avatar: 'https://i.pravatar.cc/150?img=12',
      pinnedTweetId: 0,
      isPrivateProfile: false,
      isFollower: false,
      isMyProfileBlocked: false,
      isUserBlocked: false,
      isUserMuted: false,
    },
    images: [],
    imageDescription: '',
    taggedImageUsers: [],
    quoteTweet: {} as QuoteTweetResponse,
    tweetList: {} as TweetListResponse,
    poll: {} as PollResponse,
    retweetsCount: 234,
    likesCount: 567,
    repliesCount: 89,
    quotesCount: 34,
    isDeleted: false,
    isTweetLiked: true,
    isTweetRetweeted: true,
    isUserFollowByOtherUser: false,
    isTweetDeleted: false,
    isTweetBookmarked: true,
  },
  {
    id: '4',
    text: 'Anyone else debugging at 2 AM? 😅 Just me? Okay...',
    tweetType: TweetType.TWEET,
    createdAt: '2025-11-06T23:45:00Z',
    scheduledDate: '',
    addressedUsername: '',
    addressedId: 0,
    addressedTweetId: 0,
    replyType: ReplyType.EVERYONE,
    link: '',
    linkTitle: '',
    linkDescription: '',
    linkCover: '',
    linkCoverSize: LinkCoverSize.SMALL,
    gifImage: emptyGifImage,
    author: {
      id: 4,
      fullName: 'Sarah Williams',
      username: 'sarahw',
      avatar: 'https://i.pravatar.cc/150?img=20',
      pinnedTweetId: 0,
      isPrivateProfile: false,
      isFollower: true,
      isMyProfileBlocked: false,
      isUserBlocked: false,
      isUserMuted: false,
    },
    images: [],
    imageDescription: '',
    taggedImageUsers: [],
    quoteTweet: {} as QuoteTweetResponse,
    tweetList: {} as TweetListResponse,
    poll: {} as PollResponse,
    retweetsCount: 67,
    likesCount: 234,
    repliesCount: 45,
    quotesCount: 12,
    isDeleted: false,
    isTweetLiked: false,
    isTweetRetweeted: false,
    isUserFollowByOtherUser: true,
    isTweetDeleted: false,
    isTweetBookmarked: false,
  },
  {
    id: '5',
    text: 'The best way to predict the future is to create it. 🌟 Keep building, keep learning!',
    tweetType: TweetType.TWEET,
    createdAt: '2025-11-06T20:30:00Z',
    scheduledDate: '',
    addressedUsername: '',
    addressedId: 0,
    addressedTweetId: 0,
    replyType: ReplyType.EVERYONE,
    link: '',
    linkTitle: '',
    linkDescription: '',
    linkCover: '',
    linkCoverSize: LinkCoverSize.SMALL,
    gifImage: emptyGifImage,
    author: {
      id: 5,
      fullName: 'Alex Chen',
      username: 'alexchen',
      avatar: 'https://i.pravatar.cc/150?img=33',
      pinnedTweetId: 0,
      isPrivateProfile: false,
      isFollower: false,
      isMyProfileBlocked: false,
      isUserBlocked: false,
      isUserMuted: false,
    },
    images: [],
    imageDescription: '',
    taggedImageUsers: [],
    quoteTweet: {} as QuoteTweetResponse,
    tweetList: {} as TweetListResponse,
    poll: {} as PollResponse,
    retweetsCount: 456,
    likesCount: 1234,
    repliesCount: 123,
    quotesCount: 67,
    isDeleted: false,
    isTweetLiked: true,
    isTweetRetweeted: false,
    isUserFollowByOtherUser: false,
    isTweetDeleted: false,
    isTweetBookmarked: true,
  },
];
