import { LinkCoverSize, ReplyType, TweetType } from '@/types/common';
import type { TweetListResponse } from '@/types/lists';
import type {
  GifImageResponse,
  PollResponse,
  QuoteTweetResponse,
  TweetResponse,
} from '@/types/tweet';

const emptyGifImage: GifImageResponse = { url: '', width: 0, height: 0 };

export const mockTweets: TweetResponse[] = [
  {
    id: 1,
    text: 'Just launched my new project! 🚀 Excited to share it with everyone. Check it out and let me know what you think!',
    tweetType: TweetType.TWEET,
    createdAt: '2025-11-07T10:30:00Z',
    scheduledDate: '',
    addressedUsername: '',
    addressedId: 0,
    addressedTweetId: 0,
    replyType: ReplyType.EVERYONE,
    link: '',
    linkTitle: '',
    linkDescription: '',
    linkCover: '',
    linkCoverSize: LinkCoverSize.SMALL,
    gifImage: emptyGifImage,
    author: {
      id: 1,
      fullName: 'John Doe',
      username: 'johndoe',
      avatar: 'https://i.pravatar.cc/150?img=1',
      pinnedTweetId: 0,
      isPrivateProfile: false,
      isFollower: false,
      isMyProfileBlocked: false,
      isUserBlocked: false,
      isUserMuted: false,
    },
    images: [
      {
        id: 1,
        src: 'https://picsum.photos/seed/tweet1/600/400',
      },
    ],
    imageDescription: '',
    taggedImageUsers: [],
    quoteTweet: {
      id: 101,
      text: 'This is an insightful thread on building clean UIs. Read and enjoy!',
      createdAt: '2025-11-05T14:20:00Z',
      link: '',
      linkTitle: '',
      linkDescription: '',
      linkCover: '',
      linkCoverSize: 'SMALL',
      isDeleted: false,
      author: {
        id: 11,
        fullName: 'Design Team',
        username: 'designdev',
        avatar: 'https://i.pravatar.cc/150?img=45',
        pinnedTweetId: 0,
        isPrivateProfile: false,
        isFollower: false,
        isMyProfileBlocked: false,
        isUserBlocked: false,
        isUserMuted: false,
      },
    } as QuoteTweetResponse,
    tweetList: {
      id: 201,
      listName: 'Frontend Engineers',
      altWallpaper: 'https://picsum.photos/seed/list1/800/200',
      wallpaper: 'https://picsum.photos/seed/list1/1200/400',
      listOwner: {
        id: 21,
        fullName: 'List Owner',
        username: 'listowner',
        avatar: 'https://i.pravatar.cc/150?img=22',
        pinnedTweetId: 0,
        isPrivateProfile: false,
        isFollower: false,
        isMyProfileBlocked: false,
        isUserBlocked: false,
        isUserMuted: false,
      },
      isPrivate: false,
      membersSize: 342,
    } as TweetListResponse,
    poll: {} as PollResponse,
    reTweetsCount: 45,
    likesCount: 128,
    repliesCount: 23,
    quotesCount: 5,
    isDeleted: false,
    isTweetLiked: false,
    isTweetReTweeted: false,
    isUserFollowByOtherUser: true,
    isTweetDeleted: false,
    isTweetBookmarked: false,
  },
  {
    id: 2,
    text: 'Beautiful day for coding! ☀️ Working on some exciting features. What are you all working on today?',
    tweetType: TweetType.TWEET,
    createdAt: '2025-11-07T09:15:00Z',
    scheduledDate: '',
    addressedUsername: '',
    addressedId: 0,
    addressedTweetId: 0,
    replyType: ReplyType.EVERYONE,
    link: '',
    linkTitle: '',
    linkDescription: '',
    linkCover: '',
    linkCoverSize: LinkCoverSize.SMALL,
    gifImage: emptyGifImage,
    author: {
      id: 2,
      fullName: 'Jane Smith',
      username: 'janesmith',
      avatar: 'https://i.pravatar.cc/150?img=5',
      pinnedTweetId: 0,
      isPrivateProfile: false,
      isFollower: true,
      isMyProfileBlocked: false,
      isUserBlocked: false,
      isUserMuted: false,
    },
    images: [
      {
        id: 2,
        src: 'https://picsum.photos/seed/tweet2/600/400',
      },
    ],
    imageDescription: '',
    taggedImageUsers: [],
    quoteTweet: {
      id: 102,
      text: 'I love when small optimizations make a big UX difference.',
      createdAt: '2025-11-04T18:10:00Z',
      link: '',
      linkTitle: '',
      linkDescription: '',
      linkCover: '',
      linkCoverSize: 'SMALL',
      isDeleted: false,
      author: {
        id: 12,
        fullName: 'Frontend Dev',
        username: 'frontendpro',
        avatar: 'https://i.pravatar.cc/150?img=8',
        pinnedTweetId: 0,
        isPrivateProfile: false,
        isFollower: false,
        isMyProfileBlocked: false,
        isUserBlocked: false,
        isUserMuted: false,
      },
    } as QuoteTweetResponse,
    tweetList: {
      id: 202,
      listName: 'Design & UX',
      altWallpaper: 'https://picsum.photos/seed/list2/800/200',
      wallpaper: 'https://picsum.photos/seed/list2/1200/400',
      listOwner: {
        id: 22,
        fullName: 'UX Collective',
        username: 'uxcollective',
        avatar: 'https://i.pravatar.cc/150?img=30',
        pinnedTweetId: 0,
        isPrivateProfile: false,
        isFollower: false,
        isMyProfileBlocked: false,
        isUserBlocked: false,
        isUserMuted: false,
      },
      isPrivate: false,
      membersSize: 128,
    } as TweetListResponse,
    poll: {} as PollResponse,
    retweetsCount: 12,
    likesCount: 89,
    repliesCount: 15,
    quotesCount: 2,
    isDeleted: false,
    isTweetLiked: true,
    isTweetRetweeted: false,
    isUserFollowByOtherUser: true,
    isTweetDeleted: false,
    isTweetBookmarked: false,
  },
  {
    id: 3,
    text: 'Quick tip: Always write clean code. Your future self will thank you! 💡 #coding #tips',
    tweetType: TweetType.TWEET,
    createdAt: '2025-11-07T08:00:00Z',
    scheduledDate: '',
    addressedUsername: '',
    addressedId: 0,
    addressedTweetId: 0,
    replyType: ReplyType.EVERYONE,
    link: '',
    linkTitle: '',
    linkDescription: '',
    linkCover: '',
    linkCoverSize: LinkCoverSize.SMALL,
    gifImage: emptyGifImage,
    author: {
      id: 3,
      fullName: 'Mike Johnson',
      username: 'mikej',
      avatar: 'https://i.pravatar.cc/150?img=12',
      pinnedTweetId: 0,
      isPrivateProfile: false,
      isFollower: false,
      isMyProfileBlocked: false,
      isUserBlocked: false,
      isUserMuted: false,
    },
    images: [
      {
        id: 3,
        src: 'https://picsum.photos/seed/tweet3/600/400',
      },
    ],
    imageDescription: '',
    taggedImageUsers: [],
    quoteTweet: {
      id: 103,
      text: 'Late-night debugging session victory: fixed a nasty race condition!',
      createdAt: '2025-11-03T02:05:00Z',
      link: '',
      linkTitle: '',
      linkDescription: '',
      linkCover: '',
      linkCoverSize: 'SMALL',
      isDeleted: false,
      author: {
        id: 13,
        fullName: 'Night Coder',
        username: 'nightcoder',
        avatar: 'https://i.pravatar.cc/150?img=15',
        pinnedTweetId: 0,
        isPrivateProfile: false,
        isFollower: false,
        isMyProfileBlocked: false,
        isUserBlocked: false,
        isUserMuted: false,
      },
    } as QuoteTweetResponse,
    tweetList: {
      id: 203,
      listName: 'Night Owls',
      altWallpaper: 'https://picsum.photos/seed/list3/800/200',
      wallpaper: 'https://picsum.photos/seed/list3/1200/400',
      listOwner: {
        id: 23,
        fullName: 'Night Coder',
        username: 'nightcoder',
        avatar: 'https://i.pravatar.cc/150?img=15',
        pinnedTweetId: 0,
        isPrivateProfile: false,
        isFollower: false,
        isMyProfileBlocked: false,
        isUserBlocked: false,
        isUserMuted: false,
      },
      isPrivate: false,
      membersSize: 54,
    } as TweetListResponse,
    poll: {} as PollResponse,
    retweetsCount: 234,
    likesCount: 567,
    repliesCount: 89,
    quotesCount: 34,
    isDeleted: false,
    isTweetLiked: true,
    isTweetRetweeted: true,
    isUserFollowByOtherUser: false,
    isTweetDeleted: false,
    isTweetBookmarked: true,
  },
  {
    id: 4,
    text: 'Anyone else debugging at 2 AM? 😅 Just me? Okay...',
    tweetType: TweetType.TWEET,
    createdAt: '2025-11-06T23:45:00Z',
    scheduledDate: '',
    addressedUsername: '',
    addressedId: 0,
    addressedTweetId: 0,
    replyType: ReplyType.EVERYONE,
    link: '',
    linkTitle: '',
    linkDescription: '',
    linkCover: '',
    linkCoverSize: LinkCoverSize.SMALL,
    gifImage: emptyGifImage,
    author: {
      id: 4,
      fullName: 'Sarah Williams',
      username: 'sarahw',
      avatar: 'https://i.pravatar.cc/150?img=20',
      pinnedTweetId: 0,
      isPrivateProfile: false,
      isFollower: true,
      isMyProfileBlocked: false,
      isUserBlocked: false,
      isUserMuted: false,
    },
    images: [
      {
        id: 2,
        src: 'https://picsum.photos/seed/tweet2/600/400',
      },
    ],
    imageDescription: '',
    taggedImageUsers: [],
    quoteTweet: {} as QuoteTweetResponse,
    tweetList: {} as TweetListResponse,
    poll: {} as PollResponse,
    retweetsCount: 67,
    likesCount: 234,
    repliesCount: 45,
    quotesCount: 12,
    isDeleted: false,
    isTweetLiked: false,
    isTweetRetweeted: false,
    isUserFollowByOtherUser: true,
    isTweetDeleted: false,
    isTweetBookmarked: false,
  },
  {
    id: 5,
    text: 'The best way to predict the future is to create it. 🌟 Keep building, keep learning!',
    tweetType: TweetType.TWEET,
    createdAt: '2025-11-06T20:30:00Z',
    scheduledDate: '',
    addressedUsername: '',
    addressedId: 0,
    addressedTweetId: 0,
    replyType: ReplyType.EVERYONE,
    link: '',
    linkTitle: '',
    linkDescription: '',
    linkCover: '',
    linkCoverSize: LinkCoverSize.SMALL,
    gifImage: emptyGifImage,
    author: {
      id: 5,
      fullName: 'Alex Chen',
      username: 'alexchen',
      avatar: 'https://i.pravatar.cc/150?img=33',
      pinnedTweetId: 0,
      isPrivateProfile: false,
      isFollower: false,
      isMyProfileBlocked: false,
      isUserBlocked: false,
      isUserMuted: false,
    },
    images: [
      {
        id: 2,
        src: 'https://picsum.photos/seed/tweet2/600/400',
      },
    ],
    imageDescription: '',
    taggedImageUsers: [],
    quoteTweet: {} as QuoteTweetResponse,
    tweetList: {} as TweetListResponse,
    poll: {} as PollResponse,
    retweetsCount: 456,
    likesCount: 1234,
    repliesCount: 123,
    quotesCount: 67,
    isDeleted: false,
    isTweetLiked: true,
    isTweetRetweeted: false,
    isUserFollowByOtherUser: false,
    isTweetDeleted: false,
    isTweetBookmarked: true,
  },
];
